// src/lib/telegram.ts

const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN || "8768617595:AAHguiGNu86blD6JuEE95OoZ4ZdteynhRLg";
const TELEGRAM_CHANNEL_ID = process.env.TELEGRAM_CHANNEL_ID || "-1004310725672";
const WEBSITE_URL = "https://tradevault-sepia.vercel.app";

export async function sendTelegramSignal(signal: any) {
  try {
    const direction = signal.direction?.toUpperCase() || "LONG";
    const emoji = direction === "LONG" ? "📈" : "📉";
    
    const message = `
${emoji} *TRADEVault FREE SIGNAL*

━━━━━━━━━━━━━━━━━

📊 *Pair:* ${signal.pair}
🎯 *Direction:* ${direction}

━━━━━━━━━━━━━━━━━

💰 *Entry:* ${signal.entry}
🛑 *Stop Loss:* ${signal.stopLoss}

✅ *Take Profit 1:* ${signal.takeProfit1}

━━━━━━━━━━━━━━━━━

⏰ *Expires:* 24 hours
⚡ *Type:* ${signal.isAutoGenerated ? "AI Generated" : "Manual"}

━━━━━━━━━━━━━━━━━

🔒 *Want TP2 & TP3 with full analysis?*
👉 Join TradeVault VIP: ${WEBSITE_URL}
`;

    const response = await fetch(
      `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          chat_id: TELEGRAM_CHANNEL_ID,
          text: message,
          parse_mode: "Markdown",
        }),
      }
    );

    const data = await response.json();
    
    if (!data.ok) {
      console.error("Telegram send failed:", data.description);
      return false;
    }
    
    console.log("Signal posted to Telegram channel!");
    return true;
  } catch (error) {
    console.error("Telegram error:", error);
    return false;
  }
}