// src/app/api/admin/analytics/route.ts

import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth/session";
import { dbConnect } from "@/lib/db/mongodb";
import User from "@/lib/models/user";
import Trade from "@/lib/models/trade";
import Signal from "@/lib/models/signal";

const ADMIN_EMAIL = "normanainebyoona7@gmail.com";

export async function GET() {
  try {
    const session = await getSession();
    if (!session || session.email !== ADMIN_EMAIL) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    await dbConnect();

    // Get all users
    const users = await User.find({}).lean();

    // Get all trades
    const trades = await Trade.find({}).lean();

    // Get all signals
    const signals = await Signal.find({}).lean();

    // Calculate user performance
    const userPerformance = users.map((user: any) => {
      const userTrades = trades.filter((trade: any) => trade.userId === user._id.toString());
      
      const wins = userTrades.filter((t: any) => t.status === "win").length;
      const losses = userTrades.filter((t: any) => t.status === "loss").length;
      const breakeven = userTrades.filter((t: any) => t.status === "breakeven").length;
      const openTrades = userTrades.filter((t: any) => t.status === "open").length;
      const totalPnL = userTrades.reduce((sum: number, t: any) => sum + (t.pnl || 0), 0);
      const winRate = userTrades.length > 0 ? ((wins / (wins + losses + breakeven)) * 100).toFixed(1) : "0";
      
      const winTrades = userTrades.filter((t: any) => t.status === "win");
      const lossTrades = userTrades.filter((t: any) => t.status === "loss");
      const avgWin = winTrades.length > 0 ? winTrades.reduce((sum: number, t: any) => sum + (t.pnl || 0), 0) / winTrades.length : 0;
      const avgLoss = lossTrades.length > 0 ? lossTrades.reduce((sum: number, t: any) => sum + (t.pnl || 0), 0) / lossTrades.length : 0;
      const profitFactor = avgLoss !== 0 ? Math.abs(avgWin / avgLoss) : 0;

      // Pair performance
      const pairStats: any = {};
      userTrades.forEach((trade: any) => {
        if (!pairStats[trade.pair]) {
          pairStats[trade.pair] = { trades: 0, wins: 0, pnl: 0 };
        }
        pairStats[trade.pair].trades++;
        if (trade.status === "win") pairStats[trade.pair].wins++;
        pairStats[trade.pair].pnl += (trade.pnl || 0);
      });

      return {
        userId: user._id.toString(),
        name: user.name || "Unknown",
        email: user.email,
        tier: user.tier || "free",
        totalTrades: userTrades.length,
        wins,
        losses,
        breakeven,
        openTrades,
        winRate: Number(winRate),
        totalPnL: Number(totalPnL.toFixed(2)),
        avgWin: Number(avgWin.toFixed(2)),
        avgLoss: Number(avgLoss.toFixed(2)),
        profitFactor: Number(profitFactor.toFixed(2)),
        pairStats,
      };
    });

    // Signal generation metrics
    const signalMetrics = {
      totalSignals: signals.length,
      activeSignals: signals.filter((s: any) => s.isActive).length,
      autoGenerated: signals.filter((s: any) => s.isAutoGenerated).length,
      manualSignals: signals.filter((s: any) => !s.isAutoGenerated).length,
      byPair: Object.entries(
        signals.reduce((acc: any, s: any) => {
          acc[s.pair] = (acc[s.pair] || 0) + 1;
          return acc;
        }, {})
      ).map(([pair, count]) => ({ pair, count })),
    };

    // Overall platform stats
    const platformStats = {
      totalUsers: users.length,
      totalTrades: trades.length,
      totalSignals: signals.length,
      totalPnL: Number(trades.reduce((sum: number, t: any) => sum + (t.pnl || 0), 0).toFixed(2)),
      activeUsers: users.filter((u: any) => {
        const userTrades = trades.filter((t: any) => t.userId === u._id.toString());
        return userTrades.length > 0;
      }).length,
    };

    return NextResponse.json({
      userPerformance,
      signalMetrics,
      platformStats,
    });
  } catch (error) {
    console.error("Admin analytics error:", error);
    return NextResponse.json(
      { error: "Failed to fetch analytics" },
      { status: 500 },
    );
  }
}