// src/app/api/signals/route.ts

import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth/session";
import { dbConnect } from "@/lib/db/mongodb";
import Signal from "@/lib/models/signal";
import User from "@/lib/models/user";
import { sendTelegramSignal } from "@/lib/telegram";

export async function GET() {
  try {
    const session = await getSession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    await dbConnect();

    const user = await User.findById(session.id).lean();
    const userTier = (user as any)?.tier || "free";

    const allSignals = await Signal.find({ isActive: true })
      .sort({ createdAt: -1 })
      .lean();

    let signalsToReturn: any[] = [];

    if (userTier === "vvip") {
      signalsToReturn = allSignals;
    } else if (userTier === "vip") {
      signalsToReturn = allSignals.map((signal: any) => ({
        ...signal,
        takeProfit2: "",
        takeProfit3: "",
      }));
    } else {
      const autoSignals = allSignals
        .filter((s: any) => s.isAutoGenerated)
        .slice(0, 5);
      signalsToReturn = autoSignals.map((signal: any) => ({
        ...signal,
        takeProfit2: "",
        takeProfit3: "",
      }));
    }

    return NextResponse.json({
      signals: signalsToReturn,
      userTier,
      totalSignals: allSignals.length,
    });
  } catch (error) {
    console.error("GET signals error:", error);
    return NextResponse.json(
      { error: "Failed to fetch signals" },
      { status: 500 },
    );
  }
}

export async function POST(request: Request) {
  try {
    const session = await getSession();
    if (!session || session.email !== "normanainebyoona7@gmail.com") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const {
      pair,
      direction,
      entry,
      stopLoss,
      takeProfit1,
      takeProfit2,
      takeProfit3,
      isAutoGenerated,
    } = body;

    if (!pair || !direction || !entry || !stopLoss || !takeProfit1) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 },
      );
    }

    await dbConnect();

    const signal = await Signal.create({
      pair,
      direction,
      entry,
      stopLoss,
      takeProfit1,
      takeProfit2: takeProfit2 || "",
      takeProfit3: takeProfit3 || "",
      isActive: true,
      isAutoGenerated: isAutoGenerated || false,
    });

    // Post to Telegram channel
    await sendTelegramSignal({
      pair,
      direction,
      entry,
      stopLoss,
      takeProfit1,
      takeProfit2: takeProfit2 || "",
      takeProfit3: takeProfit3 || "",
      isAutoGenerated: isAutoGenerated || false,
    });

    return NextResponse.json({ signal }, { status: 201 });
  } catch (error) {
    console.error("POST signal error:", error);
    return NextResponse.json(
      { error: "Failed to create signal" },
      { status: 500 },
    );
  }
}