import mongoose, { Schema, Document, models } from "mongoose";

export interface ISignal extends Document {
  pair: string;
  direction: "long" | "short";
  entry: string;
  stopLoss: string;
  takeProfit1: string;
  takeProfit2: string;
  takeProfit3: string;
  isActive: boolean;
  isAutoGenerated: boolean;
  expiresAt: Date;
  createdAt: Date;
}

const SignalSchema = new Schema<ISignal>(
  {
    pair: { type: String, required: true },
    direction: { type: String, enum: ["long", "short"], required: true },
    entry: { type: String, required: true },
    stopLoss: { type: String, required: true },
    takeProfit1: { type: String, required: true },
    takeProfit2: { type: String, default: "" },
    takeProfit3: { type: String, default: "" },
    isActive: { type: Boolean, default: true },
    isAutoGenerated: { type: Boolean, default: false },
    expiresAt: { type: Date, default: () => new Date(Date.now() + 24 * 60 * 60 * 1000) },
  },
  { timestamps: true }
);

const Signal = models.Signal || mongoose.model<ISignal>("Signal", SignalSchema);

export default Signal;