import mongoose, { Schema, Document, models } from "mongoose";

export interface ISignal extends Document {
  pair: string;
  direction: "long" | "short";
  entry: string;
  stopLoss: string;
  takeProfit1: string;
  takeProfit2: string;
  takeProfit3: string;
  isActive: boolean;
  isAutoGenerated: boolean;
  expiresAt: Date;
  createdAt: Date;
  // Optional metadata
  orderType?: string;
  orderTypeDescription?: string;
  signalLabel?: string;
  zone?: {
    type: "supply" | "demand";
    top: number;
    bottom: number;
    strength?: number;
    distanceToPrice?: number;
  } | null;
  confidence?: string;
  score?: number;
  session?: string;
}

const SignalSchema = new Schema<ISignal>(
  {
    pair: { type: String, required: true },
    direction: { type: String, enum: ["long", "short"], required: true },
    entry: { type: String, required: true },
    stopLoss: { type: String, required: true },
    takeProfit1: { type: String, required: true },
    takeProfit2: { type: String, default: "" },
    takeProfit3: { type: String, default: "" },
    isActive: { type: Boolean, default: true },
    isAutoGenerated: { type: Boolean, default: false },
    expiresAt: {
      type: Date,
      default: () => new Date(Date.now() + 24 * 60 * 60 * 1000),
    },
    // Optional metadata
    orderType: { type: String, default: "MARKET" },
    orderTypeDescription: { type: String, default: "" },
    signalLabel: { type: String, default: "" },
    zone: {
      type: {
        type: String,
        enum: ["supply", "demand"],
      },
      top: Number,
      bottom: Number,
      strength: Number,
      distanceToPrice: Number,
    },
    confidence: { type: String, default: "" },
    score: { type: Number, default: 0 },
    session: { type: String, default: "" },
  },
  { timestamps: true }
);

const Signal = models.Signal || mongoose.model<ISignal>("Signal", SignalSchema);

export default Signal;